Add a gradio demo
black-forest-labs/flux pull request #18
Opened 2024-08-02 10:13 UTC by apolinario

Add a Gradio demo that runs with the original pipeline code (incl. image-to-image)

2024-08-02 15:14 UTC, jenuk requested changes
Can you also add gradio to the requirements in the pyproject-file? Please do it as a separate requirements just as the streamlit requirement? Feel free to add it to `all` too.

If you take the seed of a previous calculation and pass it through the demo again you will get a different output. If you generate another time afterwards it will give you the same image again. I'm assuming that gradio has an internal representation of that seed as a float somewhere in the middle and loses precision. This should be fixed.

2024-08-02 15:14 UTC, jenuk commented on demo_gr.py
> +            img_bytes = buffer.getvalue()
You are not using the bytes. Why calculate them? Maybe you could add an option to save generated images? Then you wouldn't get `.webp` images if you hit download in gradio.

2024-08-03 08:48 UTC, apolinario commented
> Can you also add gradio to the requirements in the pyproject-file? Please do it as a separate requirements just as the streamlit requirement? Feel free to add it to all too.

Done!

> If you take the seed of a previous calculation and pass it through the demo again you will get a different output. If you generate another time afterwards it will give you the same image again. I'm assuming that gradio has an internal representation of that seed as a float somewhere in the middle and loses precision. This should be fixed.

I found the issue. The issue is that the seed is normally calculated in Python, however when passed to the Javascript front-end, Gradio uses Javascript's `Number`, which has a maximum value of `2^53 - 1` or `9007199254740992` so if the seed is larger than that, it will replace the extra characters with zeroes 😅. The workaround I did is to do `str` in Javascript but convert to `int` for Python that can handle the larger numbers.

2024-08-03 08:49 UTC, apolinario commented
I also externalized from the advanced options accordion the image2image option!

2024-08-05 09:19 UTC, jenuk commented
Looks good! One last thing: Can you move the jpg that are generated into either a tempdir or into the `output` (or `output/gradio/`) dir that is also used in the other demos? Otherwise the script will spam the root in which it is executed.

2024-08-05 10:20 UTC, apolinario commented
Makes sense, done!

2024-08-05 11:22 UTC, zansun-nusnaz approved these changes
Thank you. Great addition!

2024-08-05 11:46 UTC, jenuk approved these changes
Thanks @apolinario for bearing with my requests. Looks top now

2024-08-05 11:47 UTC, merged